type CommitMsgType = { value: string; name: string };

const commitMsgTypes: CommitMsgType[] = [
  { value: "🎨 ", name: "🎨 改进代码的结构/格式" },
  { value: "⚡️ ", name: "⚡️ 提升性能" },
  { value: "🔥 ", name: "🔥 删除代码或文件" },
  { value: "🐛 ", name: "🐛 修复 bug" },
  { value: "🚑 ", name: "🚑 修复重要 bug" },
  { value: "✨ ", name: "✨ 引入新功能" },
  { value: "📝 ", name: "📝 添加或更新文档" },
  { value: "🚀 ", name: "🚀 部署功能" },
  { value: "💄 ", name: "💄 更新 UI 和样式文件" },
  { value: "🎉 ", name: "🎉 初次提交" },
  { value: "✅ ", name: "✅ 添加测试" },
  { value: "🔒 ", name: "🔒 修复安全问题" },
  { value: "🔐 ", name: "🔐 更改密码或密钥" },
  { value: "🔖 ", name: "🔖 发布/版本标签" },
  { value: "🚨 ", name: "🚨 移除 linter 中的警告" },
  { value: "🚧 ", name: "🚧 工作进行中" },
  { value: "💚 ", name: "💚 修复 CI 构建问题" },
  { value: "⬇️ ", name: "⬇️ 依赖降级" },
  { value: "⬆️ ", name: "⬆️ 依赖升级" },
  { value: "📌 ", name: "📌 锁定依赖版本" },
  { value: "👷 ", name: "👷 添加 CI 构建系统" },
  { value: "📈 ", name: "📈 添加分析或跟踪代码" },
  { value: "♻️ ", name: "♻️ 重构代码" },
  { value: "➕ ", name: "➕ 添加依赖" },
  { value: "➖ ", name: "➖ 删除依赖" },
  { value: "🔧 ", name: "🔧 添加或更新配置文件" },
  { value: "🔨 ", name: "🔨 更改构建流程" },
  { value: "🌐 ", name: "🌐 国际化与本地化" },
  { value: "✏️ ", name: "✏️ 修正拼写错误" },
  { value: "💩 ", name: "💩 恶心的代码" },
  { value: "⏪ ", name: "⏪ 恢复更改" },
  { value: "🔀 ", name: "🔀 合并分支" },
  { value: "📦 ", name: "📦 更新打包文件" },
  { value: "👽 ", name: "👽 由于外部 API 更改而更新代码" },
  { value: "🚚 ", name: "🚚 移动或重命名文件" },
  { value: "📄 ", name: "📄 添加或更新许可证" },
  { value: "💥 ", name: "💥 引入重大变化" },
  { value: "🍱 ", name: "🍱 添加或更新资产" },
  { value: "♿️ ", name: "♿️  改善可访问性" },
  { value: "💡 ", name: "💡 添加或更新注释" },
  { value: "🍻 ", name: "🍻 为某人买了一杯" },
  { value: "💬 ", name: "💬 更新文本和字面量" },
  { value: "🗃️ ", name: "🗃️ 执行与数据库相关的更改" },
  { value: "🔊 ", name: "🔊 添加日志" },
  { value: "🔇 ", name: "🔇 删除日志" },
  { value: "👥 ", name: "👥 添加或更新贡献者" },
  { value: "🚸 ", name: "🚸 改善用户体验/可用性" },
  { value: "🏗️ ", name: "🏗️ 进行架构更改" },
  { value: "📱 ", name: "📱 添加响应式设计" },
  { value: "🤡 ", name: "🤡 添加或更新模拟数据" },
  { value: "🥚 ", name: "🥚 添加或更新彩蛋" },
  { value: "🙈 ", name: "🙈 添加或更新 .gitignore 文件" },
  { value: "📸 ", name: "📸 添加或更新快照" },
  { value: "🔍 ", name: "🔍 改善SEO" },
  { value: "🏷️ ", name: "🏷️ 添加或更新类型" },
  { value: "🌱 ", name: "🌱 添加新种子文件" },
  { value: "🚩 ", name: "🚩 添加或更新特性标志" },
  { value: "🥅 ", name: "🥅 捕获错误" },
  { value: "💫 ", name: "💫 添加或更新动画" },
  { value: "🗑️ ", name: "🗑️ 删除未使用的代码" },
  { value: "🛂 ", name: "🛂 处理授权/权限" },
  { value: "🩹 ", name: "🩹 修复非关键性问题" },
  { value: "🧐 ", name: "🧐 添加或更新搜索功能" },
  { value: "⚰️ ", name: "⚰️ 删除死代码" },
  { value: "🧪 ", name: "🧪 添加或更新测试" },
  { value: "👔 ", name: "👔 添加或更新业务逻辑" },
  { value: "🩺 ", name: "🩺 添加或更新健康检查" },
  { value: "🧱 ", name: "🧱 基建相关变更" },
  { value: "🧑‍💻 ", name: "🧑‍💻 改善开发者体验" },
  { value: "💸 ", name: "💸 添加或更新付款/收款功能" },
  { value: "🧵 ", name: "🧵 添加或更新线程" },
  { value: "🦺 ", name: "🦺 添加或更新安全功能" },
  { value: "📦️ ", name: "📦️ 更新打包文件" },
];

export default commitMsgTypes;
